kind: Service
apiVersion: v1
metadata:
  name: manager-actor
  namespace: k8stest
spec:
  selector:
    app: manager
  ports:
  - protocol: TCP
    port: 30000
    targetPort: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: k8stest
spec:
  selector:
    matchLabels:
      app: manager
  replicas: 1
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: <your-docker-hub-username>/k8stest
        command: ["/usr/bin/java"]
        args: ["-cp", "/app/K8STest-assembly-0.1.jar", "k8stest.K8SManagerActor"]
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
          name: manager
