kind: Service
apiVersion: v1
metadata:
  name: client-actor
  namespace: k8stest
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 30000
    targetPort: client
---
apiVersion: batch/v1
kind: Job
metadata:
  name: client
  namespace: k8stest
spec:
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: <your-docker-username>/k8stest-client
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
          name: client
      restartPolicy: Never